### PR TITLE
Add - Payload encryption and include full user data into Payload (when they are encrypted)

### PR DESCRIPTION
**Pull request by cr0hn**
## Goal

- Added support of Fernet encryption of the Payload
- Once payload is encrypted, add support to include all user info into payload

## Approach

Add new authentication class that implements this feature
## New Features/Changes

Encryption by using Fernet. The rest of the features of project are unmodified and runs oks

## Example

Only encrypt Payload:

```python
    from sanic import Sanic
    from sanic_jwt import AuthenticationEncrypted, Initialize

    app = Sanic()
    app.config.ENCRYPT_PASSWORD = "ASDFAsdfkjalsdfjlkasdfjlkasdjflksaKSKSKS"
    app.config.ENCRYPT_SALT = "ASDFAsdfkjalsdfjlkasdfjlkasdjflksa"  # This is optional

    Initialize(app, authentication_class= AuthenticationEncrypted)
```

Adding all user info into Payload:

```python
    from sanic import Sanic
    from sanic_jwt import AuthenticationEncrypted, Initialize

    app = Sanic()
    app.config.ENCRYPT_PASSWORD = "ASDFAsdfkjalsdfjlkasdfjlkasdjflksaKSKSKS"
    app.config.ENCRYPT_SALT = "ASDFAsdfkjalsdfjlkasdfjlkasdjflksa"  # This is optional
    app.config.FULL_USER_INFO = True

    Initialize(app, authentication_class= AuthenticationEncrypted)
```

## Open Questions and TODOs
- [ ] Implement more encryption protocols (like AES)

### CODE REVIEW

**Comment by cr0hn** [comment]
I don't know if this feature has sense in the core of the project or as external *plugin*. I algo published the RP as external plugin:

https://github.com/cr0hn/sanic-jwt-payload-encrypt

**Comment by ahopkins** [comment]
Hmm, this is an interesting option. I will take a look at it closer in the coming days. My initial reaction is that it might work well as a plugin as you released it.

**Comment by cr0hn** [comment]
This PR has outdated code. After that I published the patches in the other repo, sorry about that!

I thought it should be easier to maintain two different repositories.

It should be great if you want to collaborate in the encryption plugin.

**Comment by ahopkins** [comment]
Sounds good. I will close this PR. We can add a note about integrating the encryption into the `sanic-jwt` docs, and then decide at a later date whether to merge.

**Comment by ahopkins** [comment]
> It should be great if you want to collaborate in the encryption plugin.

Is there some specific integration point you have a question on?

**Comment by cr0hn** [comment]
Currently only have in the TODO add AES support.

https://github.com/cr0hn/sanic-jwt-payload-encrypt/blob/master/TODO.rst

**Comment by ahopkins** [comment]
Okay. I'll take a Look. If you want, feel free to add a PR to update the docs here with integration steps.

**Pull request closed without merging**
