### PR TITLE
added new functionality and test coverage as described in #16 and #45

### PR DESCRIPTION
**Pull request by vltr**
I still have to clean up some tests (tldr; reusing fixtures) and see if I'm capable of increase the coverage (it's 81% covered now), with `validators` in need of some care. Also, if you look [here](https://github.com/vltr/sanic-jwt/blob/e1e3d988f70565287475972cb232d6502935b126/sanic_jwt/authentication.py#L21) and [here](https://github.com/vltr/sanic-jwt/blob/e1e3d988f70565287475972cb232d6502935b126/sanic_jwt/authentication.py#L24) you'll see I added a `# noqa` comment because I don't think it's programmatically possible (besides monkey patching) to reach these methods with all the prior testing already in the `initialize` method; so we can leave the `noqa` mark for coverage or leave `pass` instead of raising errors ... What do you think?

### CODE REVIEW

**Comment by ahopkins** [comment]
I did see the noqa, and figured that was the reason. I'll be honest, I only looked at the code changes you made and not the tests since I am not on my computer.

**Comment by vltr** [comment]
Oops, I forgot to change `.travis.yml` for the new test call ... Just a sec!

**Comment by vltr** [comment]
From Travis:

```
tests/test_endpoints_cookies.py:248: AttributeError
```

What the heck? (Yes I'm probably talking to myself)

**Comment by vltr** [comment]
Total "wtf". I made all steps from TravisCI (at least in my machine) using Python 3.5 and 3.6 and everything went well ...

@ahopkins can you try it at your side to see if it breaks like TravisCI?

**Comment by vltr** [comment]
> I did see the noqa, and figured that was the reason. I'll be honest, I only looked at the code changes you made and not the tests since I am not on my computer.

No problem, when you're at your computer you can do it ... As I called for help in the previous comment :stuck_out_tongue_winking_eye:

**Comment by ahopkins** [comment]
🙃

**Comment by vltr** [comment]
Warning: I left a trail of comments everywhere ...

**Comment by vltr** [comment]
@ahopkins I found the problem that was causing the tests to break in Travis ... There was a commit between works where the signature of the method `get_refresh_token` in `authenticate.py` changed from `get_refresh_token(self, user)` to `get_refresh_token(self, request, user)`, but in `blueprint.py`, method `authenticate`, it was still being called as `get_refresh_token(user, request)`, causing the problem :wink:

**Comment by ahopkins** [comment]
@vltr Makes sense. See #44 for discussion about that change.

**Pull request merged**
