### PR TITLE
Update branch with latest changes

### PR DESCRIPTION
**Pull request by ahopkins**

### CODE REVIEW

**Comment by ahopkins** [comment]
@vltr I want you to take a look so you sort of see what direction I am going with this. It is still a mess, tests are not passing yet, etc. Really, it is the `initialization.Initialize` class that is the newbie.

In starting to get things rolling, I realized I hate the way `config` is being attached and utilized in SO many different ways.

Therefore, I am going to refactor it so that config is an instance (setup by `Initialize`), but can be imported anywhere `from sanic_jwt import config`.

This way we don't need `self.app.config`, or `authenticator.app.config` or `request.app.config`.

**Comment by vltr** [comment]
> I realized I hate the way config is being attached and utilized in SO many different ways.

Yeap, I feel your pain. In my app config, I have a JSON file with something like this:
```json
"sanic_config": {
    [truncated]
    "SANIC_JWT_COOKIE_DOMAIN": "domain.tld",
    "SANIC_JWT_REFRESH_TOKEN_ENABLED": true,
    "SANIC_JWT_CLAIM_IAT": true,
    "SANIC_JWT_COOKIE_SET": true,
    "SANIC_JWT_COOKIE_STRICT": false,
    "SANIC_JWT_SECRET": "that something no one should know",
    [truncated]
}
```

And I simply apply it to the app in the most simple way possible:

```python
for k, v in sanic_config.items():
    setattr(app.config, k, v)
```

And, of course, I can't follow [Sanic guidelines](http://sanic.readthedocs.io/en/latest/sanic/config.html#loading-configuration) to load my configuration since my app have other usages and the web server is only a part of it. For my app I use Python 3.6+ and I do make usage of type hinting with a little help from [pydantic](https://pydantic-docs.helpmanual.io/), but it won't work with Python 3.5 nor I want to add any new dependency to this project :sweat_smile:

I'll dig a little bit into this and get back to you - I have to address #49 inside the config, too.

> It is still a mess, tests are not passing yet, etc.

Of course, let's keep into this branch for a while until we figure things out. I'll add comments to the code as soon as I can - there's been a development in here which is keeping me way too busy :unamused:

**Comment by vltr** [comment]
Sorry, I had to solve a bit of a "_crisis_" in here - let's say some paid service provider changed their WSDL signature without any backward compatibility, published into production and notified no one. In the middle of the day. I'm feeling like a [zombie groaning "Imhotep"](https://media.giphy.com/media/BihrFkdR0Qqn6/giphy.gif) ...

I'll check the `initialization` branch today and give you my thoughts asap :wink:

**Comment by ahopkins** [comment]
@vltr No worries. I am still working to clean this all up. I have a lot more changes planned, and the deeper I get into the rabbit hole ... well, I am sure you know how it is.

**Comment by vltr** [comment]
@ahopkins yeap, sorry, I couldn't manage to see anything after all - despite all the e-mails. I'm reading them all now to get back on track.

**Comment by ahopkins** [comment]
@vltr Good luck. I hope I did not overwhelm you. There was a lot of changes.

**Comment by vltr** [comment]
No problem. I'm giving a quick shot on things I really want to be clear about ... Let's see if I can do that :sweat_smile:

**Pull request merged**
